#!/usr/bin/env bash

# Runs at the end of git flow release start
#
# Positional arguments:
# $1 The version (including the version prefix)
# $2 The origin remote
# $3 The full branch name (including the release prefix)
# $4 The base from which this release is started
#
# The following variables are available as they are exported by git-flow:
#
# MASTER_BRANCH - The branch defined as Master
# DEVELOP_BRANCH - The branch defined as Develop

VERSION=$1
ORIGIN=$2
BRANCH=$3

# Implement your script here.

SCRIPT_PATH="$0"; while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
. "$(dirname $SCRIPT_PATH)/modules/functions.sh"

. "$HOOKS_DIR/modules/add-date-to-changelog.sh"
if [ $? -ne 0 ]; then
    exit 1
fi
git commit ${ROOT_DIR}/CHANGELOG.md -m "git-flow: update changelog version and date."
if [ $? -ne 0 ]; then
	__print_fail "failed to commit CHANGELOG"
    exit 1
fi

# To terminate the git-flow action, return a non-zero exit code.
exit 0